import PathFinder from 'geojson-path-finder';

import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import Feature from 'ol/Feature';
import LineString from 'ol/geom/LineString';
import Point from 'ol/geom/Point';
import { Style, Stroke, Circle, Fill } from 'ol/style';
import { toLonLat, fromLonLat } from 'ol/proj';
import { distance } from 'ol/coordinate.js';
import { getCenter } from 'ol/extent';

import { map, setIgnoreFeatureClick, getFeatureSelected, search } from './resources/qgis2web';
import { json_mkworldroad_5 } from './layers/mkworldroad_5';
import { jsonSource_mkworldroad_5, lyr_mkworldbuild_4, pointSelectSource } from './layers/layers';
import { buildInfo } from './resources/building-info.js';


// 1. Initialize the PathFinder with your exported QGIS GeoJSON network object
// Ensure your coordinates are in WGS 84 (EPSG:4326) [Longitude, Latitude]
const pathFinder = new PathFinder(json_mkworldroad_5);

// 2. Setup a Vector Layer to hold our route line
const routeSource = new VectorSource();
const routeLayer = new VectorLayer({
    source: routeSource,
    style: new Style({
        stroke: new Stroke({
            color: '#ff3333',
            width: 5
        }),
        image: new Circle({
            radius: 6,
            fill: new Fill({
                color: '#ff3333'
            }),
            stroke: new Stroke({
                color: '#ffffff', width: 2
            })
        })
    })
});
map.addLayer(routeLayer); // 'map' is the OpenLayers map instance generated by qgis2web

const btnStartLoc = document.getElementById("btn-start-loc");
const btnEndLoc = document.getElementById("btn-end-loc")

const resList = document.getElementById("ul-search-res");

let startCoord = null;
let startCoordOL = null;
let startFeature = null;
let endCoord = null;
let endCoordOL = null;
let endFeature = null;

let routeFeature = null;

var globalPointMode = 0; // 0 = none, 1 = start, 2 = end

function assignCoordAsPoint(clickedCoord, pointMode){
    // 2. Find the closest road feature in your QGIS road layer
    // (Replace 'lyr_roads_1' with the actual OpenLayers layer variable name from qgis2web)
    let firstClosestFeature = jsonSource_mkworldroad_5.getClosestFeatureToCoordinate(clickedCoord);
    if (!firstClosestFeature) return false;
    
    // Check until the closest non-rail feature is found
    let closestFeature = firstClosestFeature;
    if(firstClosestFeature.get("type")==="rail"){
        let checkedFeat = [];
        closestFeature = jsonSource_mkworldroad_5.getClosestFeatureToCoordinate(clickedCoord, feature =>  {
            const res = (!checkedFeat.includes(feature) && feature.get("type")!=="rail");
            checkedFeat.push(feature);
            return res;
        });
    }

    // 3. Get the exact coordinate on that road closest to the click
    const closestGeometry = closestFeature.getGeometry();
    const snapLineCoordOL = closestGeometry.getClosestPoint(clickedCoord);
    // If distance is too far, ignore
    if(distance(clickedCoord, snapLineCoordOL) > 100) return false;
    // Replace closestGeometry.getClosestPoint(clickedCoord) with this:
    const lineCoordinates = closestGeometry.getCoordinates();
    let closestVertex = null;
    let minDistance = Infinity;

    // For MultiLineStrings, you might need to flatten or loop through segments
    // This example assumes a simple LineString for demonstration:
    lineCoordinates.forEach(vertex => {
        const line = new LineString([clickedCoord, vertex]);
        const distance = line.getLength();
        //const distance = ol.coordinate.distance(clickedCoord, vertex);
        //console.log(ol.coordinate.distance)
        if (distance < minDistance) {
            minDistance = distance;
            closestVertex = vertex;
        }
    });

    // Use closestVertex (which is an actual node in your GeoJSON) instead of the mid-line point
    const snappedCoordOL = closestVertex;

    // 4. Transform this snapped coordinate to WGS 84 for the path finder
    let snappedCoordLonLat = toLonLat(snappedCoordOL);

    if(pointMode==1){
        startCoord = snappedCoordLonLat;
        startCoordOL = snapLineCoordOL;
        //startCoord = [0.01612802, -0.02746810]
        console.log("Snapped Start point:", startCoord);

        // Create the point using the map's native projection coordinate (snappedCoordOL)
        if(startFeature) routeSource.removeFeature(startFeature);
        if(routeFeature){
            routeSource.removeFeature(routeFeature);
            routeFeature = null;
        }
        startFeature = new Feature({
            geometry: new Point(snapLineCoordOL)
        });
        routeSource.addFeature(startFeature);
        document.getElementById("span-start-loc").textContent = "Point set";
        btnStartLoc.classList.remove("setting-route");
    }
    else if(pointMode==2){
        endCoord = snappedCoordLonLat//[0.01975699, -0.02867173]//snappedCoordLonLat;
        endCoordOL = snapLineCoordOL;
        console.log("Snapped End point:", endCoord);
        // Create the point using the map's native projection coordinate (snappedCoordOL)
        if(endFeature) routeSource.removeFeature(endFeature);
        if(routeFeature){
            routeSource.removeFeature(routeFeature);
            routeFeature = null;
        }
        endFeature = new Feature({
            geometry: new Point(snapLineCoordOL)
        });
        routeSource.addFeature(endFeature);
        document.getElementById("span-end-loc").textContent = "Point set";
        btnEndLoc.classList.remove("setting-route");
    }

    resList.classList.remove("isRouting");
    resList.classList.add("hidden");
    document.getElementById("div-route-search").style.display = "none";
    return true;
}

// 3. Listen for clicks on the map to set Start and End points
map.on('singleclick', function (evt) {
    const clickedCoord = evt.coordinate;
    if(!assignCoordAsPoint(clickedCoord, globalPointMode)) return;
    // console.log("Snapped")
    globalPointMode = 0;
});

function startRoute(){
    document.getElementById("div-info").classList.remove("showinfo");
    document.getElementById("div-route-finder").classList.remove('hidden');
    document.getElementById("div-topbar").classList.add('hidden');
    document.getElementById("div-map-action").classList.add('hidden');
    document.getElementById("div-route-search").style.display = "none";
    resList.classList.add("hidden");
    setIgnoreFeatureClick(true);
    // Clear old points and lines so they don't pile up
    pointSelectSource.clear();
    routeSource.clear();
    globalPointMode = 0;
    startCoord = null;
    startCoordOL = null;
    endCoord = null;
    endCoordOL = null;
    document.getElementById("span-start-loc").textContent = "Not set";
    document.getElementById("span-end-loc").textContent = "Not set";

    // Check if feature selected
    const featureSelected = getFeatureSelected();
    if(featureSelected.length>0){
        assignCoordAsPoint(getCenter(featureSelected[0].getGeometry().getExtent()), 2);
        document.getElementById("span-end-loc").textContent = featureSelected[0].get('text');
    }
}

document.getElementById("btn-routes").addEventListener('click', startRoute);
document.getElementById("btn-routes-d").addEventListener('click', startRoute);
document.getElementById("btn-routehere").addEventListener('click', startRoute);
document.getElementById('btn-routes-cancel').addEventListener('click', () => {
    document.getElementById("div-route-finder").classList.add('hidden');
    document.getElementById("div-topbar").classList.remove('hidden');
    document.getElementById("div-map-action").classList.remove('hidden');
    routeSource.clear();
    resList.classList.remove("isRouting");
    resList.classList.add("hidden");
    document.getElementById("div-route-search").style.display = "none";
    setIgnoreFeatureClick(false);
})

btnStartLoc.addEventListener('click', () => {
    globalPointMode = 1;
    document.getElementById("div-route-search").style.display = "block";
    resList.classList.add("isRouting");
    btnStartLoc.classList.add("setting-route");
});
btnEndLoc.addEventListener('click', () => {
    globalPointMode = 2;
    document.getElementById("div-route-search").style.display = "block";
    resList.classList.add("isRouting");
    btnEndLoc.classList.add("setting-route");
});

document.getElementById("btn-route-search").addEventListener('click', () => {
    search(document.getElementById("input-route-search").value, foundFeat => {
        assignCoordAsPoint(getCenter(foundFeat.getGeometry().getExtent()), globalPointMode);
        resList.classList.add("hidden");
    });
});

document.getElementById("input-route-search").addEventListener('keydown', evt => {
    if(evt.key==="Enter"){
        search(document.getElementById("input-route-search").value, foundFeat => {
            assignCoordAsPoint(getCenter(foundFeat.getGeometry().getExtent()), globalPointMode);
            resList.classList.add("hidden");
        });
    }
})

document.getElementById("btn-find-route").addEventListener('click', () => {
    if(startCoord && endCoord){
        // Define GeoJSON point formats for the finder
        const startPoint = {
            type: 'Feature',
            geometry: {
                type: 'Point',
                coordinates: startCoord
            }
        };
        const endPoint = {
            type: 'Feature',
            geometry: {
                type: 'Point',
                coordinates: endCoord
            }
        };

        // 4. Calculate the path
        const result = pathFinder.findPath(startPoint, endPoint);

        if (result && result.path) {
            console.log("Success");
            // Convert the result array of coordinates back to a format OpenLayers understands
            // geojson-path-finder exports coordinates as [lng, lat]
            const olCoordinates = result.path.map(coord => fromLonLat(coord));

            if (olCoordinates.length > 1) {
                olCoordinates.unshift(startCoordOL);
                olCoordinates.push(endCoordOL);
            }

            // 4. Render the trimmed line onto your OpenLayers map
            if(routeFeature) routeSource.removeFeature(routeFeature);
            routeFeature = new Feature({
                geometry: new LineString(olCoordinates)
            });

            routeSource.addFeature(routeFeature);

            map.getView().fit(routeFeature.getGeometry());
        } else {
            alert("Could not find a valid route between these two points. Check your topology!");
        }

        // Reset for the next routing attempt
        startCoord = null;
    }
    else{
        alert("Please set the start and / or the end point.");
    }
})